# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/genFormat.ipynb (unless otherwise specified).

__all__ = ['askGroot']

# Cell

#imports
import math

# Cell

def askGroot(Question):

    if(type(Question) == str):
        response = "I am Groot"
    else:
        response = "i am groot?"
    return response