# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_data.management.core.ipynb (unless otherwise specified).

__all__ = ['F_EXT_TO_LANG', 'Class', 'Method', 'Document', 'Requirement']

# Cell
from pathlib import Path
from pydantic import BaseModel
from typing import List, Optional

# Cell
F_EXT_TO_LANG = {
    ".java": "Java",
    ".py": "Python",
    ".cpp": "C++",
    ".c": "C",
    ".js": "Javascript",
}

# Cell
class Class(BaseModel):
    text: str
    lang: str
    instance_vars: Optional[List[str]] = []
    methods: Optional[List[str]] = []

    @staticmethod
    def from_file(fpath: Path):
        with open(fpath, "r") as f:
            text = f.read()
        lang = F_EXT_TO_LANG[fpath.suffix]
        return Class(text=text, lang=lang)


class Method:
    text: str
    lang: str

# Cell
class Document:
    text: str
    lang: str


class Requirement:
    text: str
    pass