# AUTOGENERATED! DO NOT EDIT! File to edit: dev/24_mgmnt.corpus.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
import unittest
import random
from nltk.stem.snowball import SnowballStemmer