# AUTOGENERATED! DO NOT EDIT! File to edit: dev/2.0_repr.codebert.ipynb (unless otherwise specified).

__all__ = []

# Cell
# Imports
import torch
from transformers import RobertaTokenizer, RobertaConfig, RobertaModel