# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_data.core.ipynb (unless otherwise specified).

__all__ = ['Class', 'Method', 'Document', 'Requirement']

# Cell
class Class:
    pass

class Method:
    pass

# Cell
class Document:
    pass

class Requirement:
    pass