# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"df_to_txt_file": "00_data.preprocessing.ipynb",
         "gen_sp_model": "00_data.preprocessing.ipynb"}

modules = ["data/preprocessing.py"]

git_url = "https://github.com/ncoop57/ds4se/tree/master/"

def custom_doc_links(name): return None
